### ISSUE TITLE
pushmsixscript fails: configparser.NoOptionError: No option 'codename' in section: 'App'

### ISSUE THREAD

**Issue by gbrownmozilla** [escapewindow/scriptworker-scripts#461]
From first run of pushmsixscript on mozilla-beta:
```
2022-01-26 01:29:39,079 - pushmsixscript.script - INFO - found msix at /app/workdir/cot/EWA26qfOQeSaxemWOiZmjA/public/build/target.store.msix
2022-01-26 01:29:41,523 - pushmsixscript.manifest - INFO - Archive version: 97.0.8.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'codename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/pushmsixscript", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/pushmsixscript/script.py", line 42, in main
    return client.sync_main(async_main, config_path=config_path, default_config=get_default_config())
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 127, in sync_main
    loop.run_until_complete(_handle_asyncio_loop(async_main, config, task))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 182, in _handle_asyncio_loop
    await async_main(config, task)
  File "/app/lib/python3.9/site-packages/pushmsixscript/script.py", line 18, in async_main
    manifest.verify_msix(msix_file_path)
  File "/app/lib/python3.9/site-packages/pushmsixscript/manifest.py", line 48, in verify_msix
    code_name = config.get("App", "CodeName")
  File "/usr/local/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'codename' in section: 'App'
exit code: 1
```

**Comment by gbrownmozilla** [comment]
I verified there is no App / CodeName entry in that build's application.ini. I hadn't realized that entry is optional:
https://searchfox.org/mozilla-central/rev/7fb9750a14e99267a77328559c2fd022e360d99b/build/application.ini.in#22-24

That's okay - I was only reporting CodeName (like "Firefox Nightly") for diagnostic purposes.
