### ISSUE TITLE
[pushmsixscript] Failure in staging: "jsonschema.exceptions.ValidationError: [] is too short"

### ISSUE THREAD

**Issue by gbrownmozilla** [escapewindow/scriptworker-scripts#523]
https://firefox-ci-tc.services.mozilla.com/tasks/EQNZVH-JSe2AFXePz1Rhvw/runs/0/logs/public/logs/live_backing.log
```
Traceback (most recent call last):
  File "/app/bin/pushmsixscript", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/pushmsixscript/script.py", line 44, in main
    return client.sync_main(async_main, config_path=config_path, default_config=get_default_config())
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 125, in sync_main
    verify_task_schema(config, task)
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 86, in verify_task_schema
    verify_json_schema(task, task_schema)
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 59, in verify_json_schema
    raise TaskVerificationError(
scriptworker_client.exceptions.TaskVerificationError: Can't verify task schema!
[] is too short
Failed validating 'minItems' in schema['properties']['scopes']:
    {'items': {'type': 'string'},
     'minItems': 1,
     'type': 'array',
     'uniqueItems': True}
On instance['scopes']:
    []
exit code: 1
```

**Comment by gbrownmozilla** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/EQNZVH-JSe2AFXePz1Rhvw/runs/0
```
{
  "provisionerId": "scriptworker-k8s",
  "workerType": "gecko-1-pushmsix",
  "taskQueueId": "scriptworker-k8s/gecko-1-pushmsix",
  "schedulerId": "gecko-level-1",
  "projectId": "none",
  "taskGroupId": "HA0U3EFjToe4hG6S0IWODA",
  "dependencies": [
    "DR_kC-HiR8qprq7xR3LXvg",
    "RGWtuZrtTpWk5zjaG051eA",
    "HA0U3EFjToe4hG6S0IWODA"
  ],
  "requires": "all-completed",
  "routes": [
    "tc-treeherder.v2.try.470c757ad060be192d468d4ab191a5fbb1ece14f"
  ],
  "priority": "very-low",
  "retries": 5,
  "created": "2022-06-03T14:57:19.055Z",
  "deadline": "2022-06-04T14:57:19.055Z",
  "expires": "2022-07-01T14:57:19.055Z",
  "scopes": [],
  "payload": {
    "channel": "beta",
    "publishMode": "Immediate",
    "upstreamArtifacts": [
      {
        "paths": [
          "public/build/target.store.msix"
        ],
        "taskId": "RGWtuZrtTpWk5zjaG051eA",
        "taskType": "build"
      },
      {
        "paths": [
          "public/build/target.store.msix"
        ],
        "taskId": "DR_kC-HiR8qprq7xR3LXvg",
        "taskType": "build"
      }
    ]
  },
  "metadata": {
    "name": "release-msix-push-firefox",
    "owner": "jcristau@mozilla.com",
    "source": "https://hg.mozilla.org/try/file/470c757ad060be192d468d4ab191a5fbb1ece14f/taskcluster/ci/release-msix-push",
    "description": "Pushes msix archives to Microsoft Store ([Treeherder job](https://treeherder.mozilla.org/#/jobs?repo=try&revision=470c757ad060be192d468d4ab191a5fbb1ece14f&selectedTaskRun=EQNZVH-JSe2AFXePz1Rhvw))"
  },
  "tags": {
    "kind": "release-msix-push",
    "label": "release-msix-push-firefox",
    "retrigger": "false",
    "createdForUser": "jcristau@mozilla.com"
  },
  "extra": {
    "index": {
      "rank": 0
    },
    "parent": "HA0U3EFjToe4hG6S0IWODA",
    "treeherder": {
      "tier": 2,
      "symbol": "push",
      "jobKind": "build",
      "machine": {
        "platform": "win32-shippable"
      },
      "groupName": "Repack into MSIX package",
      "collection": {
        "opt": true
      },
      "groupSymbol": "MSIX"
    },
    "treeherder-platform": "win32-shippable/opt"
  }
}
```

**Comment by gbrownmozilla** [comment]
I roughly imitated the flathub push when setting up msix scopes. The flathub push task in that same treeherder push has the correct behavior: the script runs, reports that it is not allowed to push, and exits cleanly. That task also has [] scopes:
https://firefox-ci-tc.services.mozilla.com/tasks/Ose1jNRvSn6Nc7A03nAZ1g/definition
but the schema allows for 0 scopes:
https://firefox-ci-tc.services.mozilla.com/tasks/Ose1jNRvSn6Nc7A03nAZ1g/runs/0/logs/public/logs/live_backing.log
```
2022-06-03 14:59:55,817 - scriptworker.client - DEBUG - Task is validated against this schema: {'title': 'Taskcluster PushFlatpak task minimal schema', 'type': 'object', 'properties': {'dependencies': {'type': 'array', 'minItems': 1, 'uniqueItems': True, 'items': {'type': 'string'}}, 'scopes': {'type': 'array', 'uniqueItems': True, 'items': {'type': 'string'}}, 'payload': {'type': 'object', 'properties': {'channel': {'type': 'string'}, 'upstreamArtifacts': {'type': 'array', 'items': {'type': 'object', 'properties': {'taskType': {'type': 'string'}, 'taskId': {'type': 'string'}, 'paths': {'type': 'array', 'minItems': 1, 'uniqueItems': True, 'items': {'type': 'string'}}}, 'required': ['taskId', 'taskType', 'paths'], 'additionalProperties': False}, 'minItems': 1, 'uniqueItems': True}}, 'required': ['upstreamArtifacts'], 'additionalProperties': False}}, 'required': ['dependencies', 'scopes', 'payload']}
```
